version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: inventory-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: postgres_admin
      POSTGRES_PASSWORD: super_secure_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory-network
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8889:8080
  redis-cache:
    image: redis:7-alpine
    container_name: inventory-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes # Guarantees data durability on restarts
    networks:
      - inventory-network

  spring-app:
    build: .
    container_name: inventory-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
      - redis-cache
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/inventory_db
      - SPRING_DATASOURCE_USERNAME=postgres_admin
      - SPRING_DATASOURCE_PASSWORD=super_secure_password
      - SPRING_DATA_REDIS_HOST=redis-cache
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - inventory-network

volumes:
  postgres_data:
  redis_data:

networks:
  inventory-network:
    driver: bridge