spring:
  application:
    name: inventoryManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/inventory
    username: postgres
    password: a
  data:
    redis:
      host: redis-cache
      port: 6379
      timeout: 60000
  #    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: 7QnL9vX2aT8mYpR4kJ6sW1eH5uB3zNcF8dGhK2LmP9rTxVq
  expiration: 86400000

